#!/usr/bin/env python3
"""Validate that the tracked bootstrap definition is self-contained."""

from __future__ import annotations

import json
from pathlib import Path

from config_layers import load_app_catalog


ROOT = Path(__file__).resolve().parents[1]
REQUIRED_FILES = [
    "SKILL.md",
    "README.md",
    "LICENSE",
    "SECURITY.md",
    "CONTRIBUTING.md",
    "CODE_OF_CONDUCT.md",
    "CHANGELOG.md",
    "THIRD_PARTY_NOTICES.md",
    ".github/ISSUE_TEMPLATE/config.yml",
    ".github/ISSUE_TEMPLATE/bug_report.yml",
    ".github/ISSUE_TEMPLATE/feature_request.yml",
    ".github/PULL_REQUEST_TEMPLATE.md",
    "state/README.md",
    "state/locator.json",
    "examples/private/manifest.json",
    "examples/private/chrome-profiles.json",
    "examples/private/app-catalog-overlay.json",
    "examples/private/dock-order.json",
    "examples/private/system-preferences-values.json",
    "examples/private/keyboard.yaml",
    "examples/private/storage-policy.json",
    "examples/private/keyboards/example-keyboard.yaml",
    "references/app-catalog.json",
    "references/configuration-layers.md",
    "references/release-acceptance-matrix.json",
    "references/testing-contract.md",
    "references/mutation-contracts.json",
    "references/mutation-transaction-contract.md",
    "references/component-state-boundary.md",
    "references/source-policy.json",
    "references/source-policy.md",
    "references/clean-mac-acceptance.json",
    "references/clean-mac-acceptance-status.json",
    "references/clean-mac-release-acceptance.md",
    "references/cli-identity.json",
    "references/macomrade-cli.md",
    "references/schema-registry.json",
    "references/schema-and-migration.md",
    "references/redacted-diagnostic-bundle.md",
    "references/machine-role-profiles.md",
    "references/localization-accessibility.md",
    "references/app-adapter-sdk.md",
    "references/performance-benchmarks.md",
    "references/audit-reports.md",
    "references/drift-monitor.md",
    "references/storage-lifecycle.md",
    "references/public-release-readiness.md",
    "references/public-onboarding.md",
    "references/public-support-safety.md",
    "references/release-manifest.md",
    "schemas/catalog-v1.schema.json",
    "schemas/settings-v1.schema.json",
    "schemas/private-overlay-v1.schema.json",
    "schemas/app-plan-v1.schema.json",
    "schemas/state-record-v1.schema.json",
    "schemas/diagnostic-result-v1.schema.json",
    "schemas/diagnostic-bundle-v1.schema.json",
    "schemas/machine-role-catalog-v1.schema.json",
    "schemas/localization-catalog-v1.schema.json",
    "schemas/app-adapter-catalog-v1.schema.json",
    "schemas/performance-budget-v1.schema.json",
    "schemas/drift-monitor-policy-v1.schema.json",
    "schemas/publication-audit-policy-v1.schema.json",
    "schemas/release-manifest-v1.schema.json",
    "schemas/storage-policy-v1.schema.json",
    "schemas/storage-scan-v1.schema.json",
    "schemas/storage-decision-ledger-v1.schema.json",
    "schemas/storage-plan-v1.schema.json",
    "schemas/storage-transaction-v1.schema.json",
    "references/runtime-and-developer-baseline.md",
    "references/permissions-preferences-bootstrap.md",
    "references/keyboard-and-logitech.md",
    "references/startup-dock-and-security.md",
    "references/application-installation-workflow.md",
    "references/application-maintenance.md",
    "settings/privacy.yaml",
    "settings/system-preferences.yaml",
    "settings/system-preferences-values.json",
    "settings/manual-actions.yaml",
    "settings/dock-order.json",
    "settings/keyboard.yaml",
    "settings/keyboards/logitech-k240-japanese-dictation.yaml",
    "settings/machine-roles.json",
    "settings/localization.json",
    "settings/app-adapters.json",
    "settings/performance-budgets.json",
    "settings/drift-monitor.json",
    "settings/publication-audit-policy.json",
    "settings/storage-policy.json",
    "locales/messages.en.json",
    "locales/messages.ja.json",
    "locales/messages.zh-Hans.json",
    "references/icloud-git-integrity.md",
    "references/machine-local-state.md",
    "scripts/bootstrap_macos.py",
    "scripts/icloud_git_guard.py",
    "scripts/migrate_state.py",
    "scripts/state_paths.py",
    "scripts/macos_apps.py",
    "scripts/macos_permissions.py",
    "scripts/macos_permissions_cleanup.py",
    "scripts/macos_preferences.py",
    "scripts/validate_release_contract.py",
    "scripts/validate_skill_structure.py",
    "scripts/release_check.py",
    "scripts/transaction_contract.py",
    "scripts/validate_mutation_contracts.py",
    "scripts/component_state.py",
    "scripts/supply_chain.py",
    "scripts/clean_mac_acceptance.py",
    "scripts/macomrade.py",
    "scripts/schema_contract.py",
    "scripts/diagnostic_bundle.py",
    "scripts/machine_roles.py",
    "scripts/localization.py",
    "scripts/app_adapters.py",
    "scripts/performance_benchmark.py",
    "scripts/audit_report.py",
    "scripts/drift_monitor.py",
    "scripts/publication_audit.py",
    "scripts/release_manifest.py",
    "scripts/public_clone_rehearsal.py",
    "scripts/storage_lifecycle.py",
    "scripts/storage_metadata.swift",
    "scripts/audit_component_frontmatter.py",
    "bin/macomrade",
    "tests/fixtures/macos_apps/catalog.json",
    "tests/fixtures/macos_apps/command-responses.json",
    "tests/test_app_catalog_validation.py",
    "tests/test_macos_apps.py",
    "tests/test_platform_fixtures.py",
    "tests/test_release_check.py",
    "tests/test_mutation_contracts.py",
    "tests/test_component_state.py",
    "tests/test_supply_chain.py",
    "tests/test_clean_mac_acceptance.py",
    "tests/test_macomrade_cli.py",
    "tests/test_schema_contract.py",
    "tests/test_diagnostic_bundle.py",
    "tests/test_machine_roles.py",
    "tests/test_localization.py",
    "tests/test_app_adapters.py",
    "tests/test_performance_benchmark.py",
    "tests/test_audit_report.py",
    "tests/test_drift_monitor.py",
    "tests/test_publication_audit.py",
    "tests/test_public_onboarding.py",
    "tests/test_public_support_contract.py",
    "tests/test_release_manifest.py",
    "tests/test_public_clone_rehearsal.py",
    "tests/test_storage_lifecycle.py",
    "tests/test_macos_startup_items.py",
    "tests/fixtures/schema_contract/app-plan-v0.json",
    "tests/fixtures/schema_contract/app-plan-v1.json",
    "tests/fixtures/schema_contract/state-record-v1.json",
    "tests/fixtures/schema_contract/diagnostic-result-v1.json",
    "tests/fixtures/schema_contract/diagnostic-bundle-v1.json",
    "tests/fixtures/schema_contract/release-manifest-v1.json",
    "tests/fixtures/schema_contract/storage-scan-v1.json",
    "tests/fixtures/schema_contract/storage-decision-ledger-v1.json",
    "tests/fixtures/schema_contract/storage-plan-v1.json",
    "tests/fixtures/schema_contract/storage-transaction-v1.json",
]


def main() -> int:
    missing = [path for path in REQUIRED_FILES if not (ROOT / path).is_file()]
    catalog = load_app_catalog()
    guide_missing = []
    for app in catalog.get("apps", []):
        guide = app.get("guide")
        if guide and not (ROOT / guide).is_file():
            guide_missing.append({"name": app.get("name"), "guide": guide})
    result = {
        "mode": "tracked_definition_only",
        "state_read": False,
        "required_files": len(REQUIRED_FILES),
        "missing_files": missing,
        "catalog_apps": len(catalog.get("apps", [])),
        "missing_guides": guide_missing,
        "status": "passed" if not missing and not guide_missing else "failed",
    }
    print(json.dumps(result, ensure_ascii=False, indent=2))
    return 0 if result["status"] == "passed" else 1


if __name__ == "__main__":
    raise SystemExit(main())
